### PR TITLE
add cantera channel to environment.yml

### PR DESCRIPTION
**Pull request by g3bk47**

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
@g3bk47 the Cantera channel shouldn't be needed, since Cantera is available on conda-forge. Did it not work for you?

**Comment by rwest** [comment]
Might be certain OS/python/bumpy/hardware versions not supported or compatible with the conda-forge binaries. We recently came across this when trying to update an RMG environment.

**Comment by kyleniemeyer** [comment]
Got it. Ok, no problem!

**Comment by bryanwweber** [comment]
In particular, Conda forge does not have Windows packages

**Comment by kyleniemeyer** [comment]
@bryanwweber ah, I missed that! good to know.

**Pull request merged**
